### PR TITLE
CORE-1442: add request limits

### PR DESCRIPTION
**Pull request by slr71**
This change allows the Discovery Environment to impose a limit on the number of administrative requests of a specific type that a user may submit. The initial use case is to permit DE users to submit at most one VICE access request.

### CODE REVIEW

**Comment by slr71** [comment]
I think I'm going to change the response when the administrative request limit is exceeded. I'll  make that change then mark this PR as being ready for review.

**Comment by slr71** [comment]
This is ready for review again now. The change that I made was to make the response body returned when a request limit is reached match the format used by `app-exposer` when a concurrent job limit is reached. Since the UI already handles those responses, I thought that it would be helpful to use the same pattern here.

**Review by sri2k1us — APPROVED** [review]
LGTM. 🚢

**Comment by slr71** [comment]
Thanks for the review!

**Pull request merged**
